//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace EventReport.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EventModel : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new EventModel object using the connection string found in the 'EventModel' section of the application configuration file.
        /// </summary>
        public EventModel() : base("name=EventModel", "EventModel")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EventModel object.
        /// </summary>
        public EventModel(string connectionString) : base(connectionString, "EventModel")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EventModel object.
        /// </summary>
        public EventModel(EntityConnection connection) : base(connection, "EventModel")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EVENT_REPORT> EVENT_REPORT
        {
            get
            {
                if ((_EVENT_REPORT == null))
                {
                    _EVENT_REPORT = base.CreateObjectSet<EVENT_REPORT>("EVENT_REPORT");
                }
                return _EVENT_REPORT;
            }
        }
        private ObjectSet<EVENT_REPORT> _EVENT_REPORT;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LCL_V_EVENTREPORT> LCL_V_EVENTREPORT
        {
            get
            {
                if ((_LCL_V_EVENTREPORT == null))
                {
                    _LCL_V_EVENTREPORT = base.CreateObjectSet<LCL_V_EVENTREPORT>("LCL_V_EVENTREPORT");
                }
                return _LCL_V_EVENTREPORT;
            }
        }
        private ObjectSet<LCL_V_EVENTREPORT> _LCL_V_EVENTREPORT;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EVENT_REPORT EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEVENT_REPORT(EVENT_REPORT eVENT_REPORT)
        {
            base.AddObject("EVENT_REPORT", eVENT_REPORT);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LCL_V_EVENTREPORT EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLCL_V_EVENTREPORT(LCL_V_EVENTREPORT lCL_V_EVENTREPORT)
        {
            base.AddObject("LCL_V_EVENTREPORT", lCL_V_EVENTREPORT);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="EVENT_REPORT")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EVENT_REPORT : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EVENT_REPORT object.
        /// </summary>
        /// <param name="pATIENTEVENTPK">Initial value of the PATIENTEVENTPK property.</param>
        public static EVENT_REPORT CreateEVENT_REPORT(global::System.String pATIENTEVENTPK)
        {
            EVENT_REPORT eVENT_REPORT = new EVENT_REPORT();
            eVENT_REPORT.PATIENTEVENTPK = pATIENTEVENTPK;
            return eVENT_REPORT;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PATIENTEVENTPK
        {
            get
            {
                return _PATIENTEVENTPK;
            }
            set
            {
                if (_PATIENTEVENTPK != value)
                {
                    OnPATIENTEVENTPKChanging(value);
                    ReportPropertyChanging("PATIENTEVENTPK");
                    _PATIENTEVENTPK = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("PATIENTEVENTPK");
                    OnPATIENTEVENTPKChanged();
                }
            }
        }
        private global::System.String _PATIENTEVENTPK;
        partial void OnPATIENTEVENTPKChanging(global::System.String value);
        partial void OnPATIENTEVENTPKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String STUDYNUMBER
        {
            get
            {
                return _STUDYNUMBER;
            }
            set
            {
                OnSTUDYNUMBERChanging(value);
                ReportPropertyChanging("STUDYNUMBER");
                _STUDYNUMBER = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("STUDYNUMBER");
                OnSTUDYNUMBERChanged();
            }
        }
        private global::System.String _STUDYNUMBER;
        partial void OnSTUDYNUMBERChanging(global::System.String value);
        partial void OnSTUDYNUMBERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PATIENTSTUDYID
        {
            get
            {
                return _PATIENTSTUDYID;
            }
            set
            {
                OnPATIENTSTUDYIDChanging(value);
                ReportPropertyChanging("PATIENTSTUDYID");
                _PATIENTSTUDYID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PATIENTSTUDYID");
                OnPATIENTSTUDYIDChanged();
            }
        }
        private global::System.String _PATIENTSTUDYID;
        partial void OnPATIENTSTUDYIDChanging(global::System.String value);
        partial void OnPATIENTSTUDYIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PATIENTID
        {
            get
            {
                return _PATIENTID;
            }
            set
            {
                OnPATIENTIDChanging(value);
                ReportPropertyChanging("PATIENTID");
                _PATIENTID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PATIENTID");
                OnPATIENTIDChanged();
            }
        }
        private global::System.String _PATIENTID;
        partial void OnPATIENTIDChanging(global::System.String value);
        partial void OnPATIENTIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VISITNAME
        {
            get
            {
                return _VISITNAME;
            }
            set
            {
                OnVISITNAMEChanging(value);
                ReportPropertyChanging("VISITNAME");
                _VISITNAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VISITNAME");
                OnVISITNAMEChanged();
            }
        }
        private global::System.String _VISITNAME;
        partial void OnVISITNAMEChanging(global::System.String value);
        partial void OnVISITNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EVENTNAME
        {
            get
            {
                return _EVENTNAME;
            }
            set
            {
                OnEVENTNAMEChanging(value);
                ReportPropertyChanging("EVENTNAME");
                _EVENTNAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EVENTNAME");
                OnEVENTNAMEChanged();
            }
        }
        private global::System.String _EVENTNAME;
        partial void OnEVENTNAMEChanging(global::System.String value);
        partial void OnEVENTNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EVENTNOTE
        {
            get
            {
                return _EVENTNOTE;
            }
            set
            {
                OnEVENTNOTEChanging(value);
                ReportPropertyChanging("EVENTNOTE");
                _EVENTNOTE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EVENTNOTE");
                OnEVENTNOTEChanged();
            }
        }
        private global::System.String _EVENTNOTE;
        partial void OnEVENTNOTEChanging(global::System.String value);
        partial void OnEVENTNOTEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EVENTSTATUS
        {
            get
            {
                return _EVENTSTATUS;
            }
            set
            {
                OnEVENTSTATUSChanging(value);
                ReportPropertyChanging("EVENTSTATUS");
                _EVENTSTATUS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EVENTSTATUS");
                OnEVENTSTATUSChanged();
            }
        }
        private global::System.String _EVENTSTATUS;
        partial void OnEVENTSTATUSChanging(global::System.String value);
        partial void OnEVENTSTATUSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LAST_MODIFIED_DATE
        {
            get
            {
                return _LAST_MODIFIED_DATE;
            }
            set
            {
                OnLAST_MODIFIED_DATEChanging(value);
                ReportPropertyChanging("LAST_MODIFIED_DATE");
                _LAST_MODIFIED_DATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LAST_MODIFIED_DATE");
                OnLAST_MODIFIED_DATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _LAST_MODIFIED_DATE;
        partial void OnLAST_MODIFIED_DATEChanging(Nullable<global::System.DateTime> value);
        partial void OnLAST_MODIFIED_DATEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CREATED_ON
        {
            get
            {
                return _CREATED_ON;
            }
            set
            {
                OnCREATED_ONChanging(value);
                ReportPropertyChanging("CREATED_ON");
                _CREATED_ON = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CREATED_ON");
                OnCREATED_ONChanged();
            }
        }
        private Nullable<global::System.DateTime> _CREATED_ON;
        partial void OnCREATED_ONChanging(Nullable<global::System.DateTime> value);
        partial void OnCREATED_ONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EVENTSTAT_DATE
        {
            get
            {
                return _EVENTSTAT_DATE;
            }
            set
            {
                OnEVENTSTAT_DATEChanging(value);
                ReportPropertyChanging("EVENTSTAT_DATE");
                _EVENTSTAT_DATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EVENTSTAT_DATE");
                OnEVENTSTAT_DATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _EVENTSTAT_DATE;
        partial void OnEVENTSTAT_DATEChanging(Nullable<global::System.DateTime> value);
        partial void OnEVENTSTAT_DATEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String COMMENTS
        {
            get
            {
                return _COMMENTS;
            }
            set
            {
                OnCOMMENTSChanging(value);
                ReportPropertyChanging("COMMENTS");
                _COMMENTS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("COMMENTS");
                OnCOMMENTSChanged();
            }
        }
        private global::System.String _COMMENTS;
        partial void OnCOMMENTSChanging(global::System.String value);
        partial void OnCOMMENTSChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="LCL_V_EVENTREPORT")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LCL_V_EVENTREPORT : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LCL_V_EVENTREPORT object.
        /// </summary>
        /// <param name="pATIENTEVENTPK">Initial value of the PATIENTEVENTPK property.</param>
        public static LCL_V_EVENTREPORT CreateLCL_V_EVENTREPORT(global::System.String pATIENTEVENTPK)
        {
            LCL_V_EVENTREPORT lCL_V_EVENTREPORT = new LCL_V_EVENTREPORT();
            lCL_V_EVENTREPORT.PATIENTEVENTPK = pATIENTEVENTPK;
            return lCL_V_EVENTREPORT;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PATIENTEVENTPK
        {
            get
            {
                return _PATIENTEVENTPK;
            }
            set
            {
                if (_PATIENTEVENTPK != value)
                {
                    OnPATIENTEVENTPKChanging(value);
                    ReportPropertyChanging("PATIENTEVENTPK");
                    _PATIENTEVENTPK = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("PATIENTEVENTPK");
                    OnPATIENTEVENTPKChanged();
                }
            }
        }
        private global::System.String _PATIENTEVENTPK;
        partial void OnPATIENTEVENTPKChanging(global::System.String value);
        partial void OnPATIENTEVENTPKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String STUDYNUMBER
        {
            get
            {
                return _STUDYNUMBER;
            }
            set
            {
                OnSTUDYNUMBERChanging(value);
                ReportPropertyChanging("STUDYNUMBER");
                _STUDYNUMBER = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("STUDYNUMBER");
                OnSTUDYNUMBERChanged();
            }
        }
        private global::System.String _STUDYNUMBER;
        partial void OnSTUDYNUMBERChanging(global::System.String value);
        partial void OnSTUDYNUMBERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PATIENTSTUDYID
        {
            get
            {
                return _PATIENTSTUDYID;
            }
            set
            {
                OnPATIENTSTUDYIDChanging(value);
                ReportPropertyChanging("PATIENTSTUDYID");
                _PATIENTSTUDYID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PATIENTSTUDYID");
                OnPATIENTSTUDYIDChanged();
            }
        }
        private global::System.String _PATIENTSTUDYID;
        partial void OnPATIENTSTUDYIDChanging(global::System.String value);
        partial void OnPATIENTSTUDYIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PATIENTID
        {
            get
            {
                return _PATIENTID;
            }
            set
            {
                OnPATIENTIDChanging(value);
                ReportPropertyChanging("PATIENTID");
                _PATIENTID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PATIENTID");
                OnPATIENTIDChanged();
            }
        }
        private global::System.String _PATIENTID;
        partial void OnPATIENTIDChanging(global::System.String value);
        partial void OnPATIENTIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VISITNAME
        {
            get
            {
                return _VISITNAME;
            }
            set
            {
                OnVISITNAMEChanging(value);
                ReportPropertyChanging("VISITNAME");
                _VISITNAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VISITNAME");
                OnVISITNAMEChanged();
            }
        }
        private global::System.String _VISITNAME;
        partial void OnVISITNAMEChanging(global::System.String value);
        partial void OnVISITNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EVENTNAME
        {
            get
            {
                return _EVENTNAME;
            }
            set
            {
                OnEVENTNAMEChanging(value);
                ReportPropertyChanging("EVENTNAME");
                _EVENTNAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EVENTNAME");
                OnEVENTNAMEChanged();
            }
        }
        private global::System.String _EVENTNAME;
        partial void OnEVENTNAMEChanging(global::System.String value);
        partial void OnEVENTNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EVENTNOTE
        {
            get
            {
                return _EVENTNOTE;
            }
            set
            {
                OnEVENTNOTEChanging(value);
                ReportPropertyChanging("EVENTNOTE");
                _EVENTNOTE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EVENTNOTE");
                OnEVENTNOTEChanged();
            }
        }
        private global::System.String _EVENTNOTE;
        partial void OnEVENTNOTEChanging(global::System.String value);
        partial void OnEVENTNOTEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EVENTSTATUS
        {
            get
            {
                return _EVENTSTATUS;
            }
            set
            {
                OnEVENTSTATUSChanging(value);
                ReportPropertyChanging("EVENTSTATUS");
                _EVENTSTATUS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EVENTSTATUS");
                OnEVENTSTATUSChanged();
            }
        }
        private global::System.String _EVENTSTATUS;
        partial void OnEVENTSTATUSChanging(global::System.String value);
        partial void OnEVENTSTATUSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LAST_MODIFIED_DATE
        {
            get
            {
                return _LAST_MODIFIED_DATE;
            }
            set
            {
                OnLAST_MODIFIED_DATEChanging(value);
                ReportPropertyChanging("LAST_MODIFIED_DATE");
                _LAST_MODIFIED_DATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LAST_MODIFIED_DATE");
                OnLAST_MODIFIED_DATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _LAST_MODIFIED_DATE;
        partial void OnLAST_MODIFIED_DATEChanging(Nullable<global::System.DateTime> value);
        partial void OnLAST_MODIFIED_DATEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CREATED_ON
        {
            get
            {
                return _CREATED_ON;
            }
            set
            {
                OnCREATED_ONChanging(value);
                ReportPropertyChanging("CREATED_ON");
                _CREATED_ON = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CREATED_ON");
                OnCREATED_ONChanged();
            }
        }
        private Nullable<global::System.DateTime> _CREATED_ON;
        partial void OnCREATED_ONChanging(Nullable<global::System.DateTime> value);
        partial void OnCREATED_ONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EVENTSTAT_DATE
        {
            get
            {
                return _EVENTSTAT_DATE;
            }
            set
            {
                OnEVENTSTAT_DATEChanging(value);
                ReportPropertyChanging("EVENTSTAT_DATE");
                _EVENTSTAT_DATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EVENTSTAT_DATE");
                OnEVENTSTAT_DATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _EVENTSTAT_DATE;
        partial void OnEVENTSTAT_DATEChanging(Nullable<global::System.DateTime> value);
        partial void OnEVENTSTAT_DATEChanged();

        #endregion

    
    }

    #endregion

    
}
